# Generated by Django 3.2.5 on 2021-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210722_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tags',
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
